### ISSUE TITLE
Error when generating chunks on server 

### ISSUE THREAD

**Issue by ghost** [jaskarth/fabric-chunkpregenerator#17]
When i run a chunk generation on server after a few minutes it send the following error:
[22:20:56] [Server thread/ERROR]: No key dirt_provider in MapLike[{decorators:[],foliage_placer:{offset:{base:0,spread:2},radius:{base:2,spread:1},trunk_height:{base:1,spread:1},type:"minecraft:spruce_foliage_placer"},heightmap:"OCEAN_FLOOR",ignore_vines:1b,leaves_provider:{state:{Name:"minecraft:spruce_leaves",Properties:{distance:"7",persistent:"false"}},type:"minecraft:simple_state_provider"},max_water_depth:0,minimum_size:{limit:2,lower_size:0,type:"minecraft:two_layers_feature_size",upper_size:2},trunk_placer:{base_height:5,height_rand_a:2,height_rand_b:1,type:"minecraft:straight_trunk_placer"},trunk_provider:{state:{Name:"minecraft:spruce_log",Properties:{axis:"y"}},type:"minecraft:simple_state_provider"}}]; Input does not contain a key [type]: MapLike[{base:1,spread:1}]; Input does not contain a key [type]: MapLike[{base:0,spread:2}]; Input does not contain a key [type]: MapLike[{base:2,spread:1}]; No key sapling_provider in MapLike[{decorators:[],foliage_placer:{offset:{base:0,spread:2},radius:{base:2,spread:1},trunk_height:{base:1,spread:1},type:"minecraft:spruce_foliage_placer"},heightmap:"OCEAN_FLOOR",ignore_vines:1b,leaves_provider:{state:{Name:"minecraft:spruce_leaves",Properties:{distance:"7",persistent:"false"}},type:"minecraft:simple_state_provider"},max_water_depth:0,minimum_size:{limit:2,lower_size:0,type:"minecraft:two_layers_feature_size",upper_size:2},trunk_placer:{base_height:5,height_rand_a:2,height_rand_b:1,type:"minecraft:straight_trunk_placer"},trunk_provider:{state:{Name:"minecraft:spruce_log",Properties:{axis:"y"}},type:"minecraft:simple_state_provider"}}]; No key foliage_provider in MapLike[{decorators:[],foliage_placer:{offset:{base:0,spread:2},radius:{base:2,spread:1},trunk_height:{base:1,spread:1},type:"minecraft:spruce_foliage_placer"},heightmap:"OCEAN_FLOOR",ignore_vines:1b,leaves_provider:{state:{Name:"minecraft:spruce_leaves",Properties:{distance:"7",persistent:"false"}},type:"minecraft:simple_state_provider"},max_water_depth:0,minimum_size:{limit:2,lower_size:0,type:"minecraft:two_layers_feature_size",upper_size:2},trunk_placer:{base_height:5,height_rand_a:2,height_rand_b:1,type:"minecraft:straight_trunk_placer"},trunk_provider:{state:{Name:"minecraft:spruce_log",Properties:{axis:"y"}},type:"minecraft:simple_state_provider"}}]
[22:20:56] [Server thread/ERROR]: Exception loading structure piece with id minecraft:jigsaw
java.lang.IllegalStateException: Invalid pool element found
	at net.minecraft.class_3790.method_35448(class_3790.java:54) ~[intermediary-server.jar:?]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at net.minecraft.class_3790.<init>(class_3790.java:54) ~[intermediary-server.jar:?]
	at net.minecraft.class_3195.method_28660(class_3195.java:151) ~[intermediary-server.jar:?]
	at net.minecraft.class_2852.method_12392(class_2852.java:415) ~[intermediary-server.jar:?]
	at net.minecraft.class_2852.method_12395(class_2852.java:175) ~[intermediary-server.jar:?]
	at net.minecraft.class_3898.method_17256(class_3898.java:512) ~[intermediary-server.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764) ~[?:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:151) ~[intermediary-server.jar:?]
	at net.minecraft.class_3215$class_4212.method_18859(class_3215.java:528) ~[intermediary-server.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:125) ~[intermediary-server.jar:?]
	at net.minecraft.class_3215$class_4212.method_16075(class_3215.java:537) ~[intermediary-server.jar:?]
	at net.minecraft.class_3215.method_19492(class_3215.java:280) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:776) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:764) ~[intermediary-server.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:110) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:748) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:701) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[intermediary-server.jar:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by jaskarth** [comment]
Not related to pregeneration
